name: build-packer
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}
  PACKER_VARS: ${{ vars.PACKER_VARS }}

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: build-packer

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp.zip .
            
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Run packer
        run: | 
              cd packer/
              packer init centos_packer.pkr.hcl
              packer fmt centos_packer.pkr.hcl
              echo "$PACKER_VARS" > variables.pkvars.hcl
              packer validate -var-file="variables.pkvars.hcl" centos_packer.pkr.hcl
              packer build --force -var-file="variables.pkvars.hcl" centos_packer.pkr.hcl
