name: build-packer
env:
  DEV_DATABASE: ${{ vars.DEV_DATABASE }}
  DEV_USERNAME: ${{ vars.DEV_USERNAME}}
  DEV_PASSWORD: ${{ vars.DEV_PASSWORD }}
  GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_APPLICATION_CREDENTIALS}}

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: build-packer

    runs-on: ubuntu-latest

    env:
      DATABASE: ${{ secrets.DATABASE }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: ${{ secrets.HOST }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Environment Variables
        run: |
          touch .env
          echo "DEV_DATABASE=${{vars.DEV_DATABASE}}" >> .env
          echo "DEV_PASSWORD=${{vars.DEV_PASSWORD}}" >> .env
          echo "DEV_USERNAME=${{ vars.DEV_USERNAME}}" >> .env
          echo "DEV_HOST=127.0.0.1" >> .env
          echo "DEV_DIALECT=mysql" >> .env

      - name: Check .env file
        run: |
          if [ -f .env ]; then
            echo ".env file exists"
            cat .env
          else
            echo ".env file does not exist"
            exit 1
          fi

      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp.zip .
            
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Run packer
        run: | 
              cd packer/
              packer init centos_packer.pkr.hcl
              packer fmt centos_packer.pkr.hcl
              packer validate -var-file="variables.pkrvars.hcl" centos_packer.pkr.hcl
              packer build -var-file="variables.pkrvars.hcl" centos_packer.pkr.hcl
