name: code-compilation-test
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  build:
    name: code-compilation-test
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'
 
    - name: Install dependencies
      run: npm install
