name: integration-tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: integration-tests
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: ${{ vars.DEV_DATABASE }}
      DB_USERNAME: ${{ vars.DEV_USERNAME }}
      DB_PASSWORD: ${{ vars.DEV_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Setup Environment Variables
        run: |
          touch .env
          echo "DEV_DATABASE=${{vars.DEV_DATABASE}}" >> .env
          echo "DEV_PASSWORD=${{vars.DEV_PASSWORD}}" >> .env
          echo "DEV_USER=mana" >> .env
          echo "DEV_HOST=127.0.0.1" >> .env
          echo "DEV_DIALECT=mysql" >> .env

      - name: Check .env file
        run: |
          if [ -f .env ]; then
            echo ".env file exists"
            cat .env
          else
            echo ".env file does not exist"
            exit 1
          fi
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}
      # - name: Set up MySQL
      #   uses: ankane/setup-mariadb@v1
      #   with:
      #     database: ${{vars.DEV_DATABASE}}

      # - name: Setup DB User
      #   run: |
      #     sudo mysql -D ${{vars.DEV_DATABASE}} -e "CREATE USER 'mana'@localhost IDENTIFIED BY '${{vars.DEV_PASSWORD}}';"
      #     sudo mysql -D ${{vars.DEV_DATABASE}} -e "GRANT ALL PRIVILEGES ON ${{vars.DEV_DATABASE}}.* TO 'mana'@localhost;"
      #     sudo mysql -D ${{vars.DEV_DATABASE}} -e "FLUSH PRIVILEGES;"

      - name: Install dependencies
        run: npm install

      - name: Verify DB User
        run: |
          sudo mysql -D "${{ vars.DEV_DATABASE }}" -e "SELECT user FROM mysql.user WHERE user = 'mana';"

      - name: Run integration tests
        run: |
          npm test
