name: integration-tests
 
on:
  pull_request:
    branches:
      - main
 
jobs:
  build:
    name: integration-tests
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'
 
    - name: Setup Environment Variables
      run: |
        touch .env
        echo "DEV_DATABASE=${{vars.DEV_DATABASE}}" >> .env
        echo "DEV_PASSWORD=${{vars.DEV_PASSWORD}}" >> .env
        echo "DEV_USER=root" >> .env
        echo "DEV_HOST=127.0.0.1" >> .env
        echo "DEV_DIALECT=mysql" >> .env
 
    - name: Set up MySQL
      uses: ankane/setup-mariadb@v1
      with:
        database: ${{vars.DEV_DATABASE}}

    - name: Setup DB User
      run: |
        sudo mysql -u root -p -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{vars.DEV_PASSWORD}}';"
        sudo mysql -D ${{vars.DEV_DATABASE}} -e "GRANT ALL PRIVILEGES ON ${{vars.DEV_DATABASE}}.* TO 'root'@localhost;"
        sudo mysql -D ${{vars.DEV_DATABASE}} -e "FLUSH PRIVILEGES;"
 
    - name: Install dependencies
      run: npm install
 
    - name: Run integration tests
      run: npm test