name: validate-packer
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_APPLICATION_CREDENTIALS}}
  PACKER_VARS: ${{vars.PACKER_VARS}}

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: validate-packer

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp.zip .
            
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Packer fmt
        run: | 
              cd packer/
              packer init centos_packer.pkr.hcl
              packer fmt -check centos_packer.pkr.hcl
      
      - name: Packer validate
        run: | 
              cd packer/
              packer init centos_packer.pkr.hcl
              packer fmt -check centos_packer.pkr.hcl
              echo "$PACKER_VARS" > variables.tfvars.hcl
              packer validate -var-file=variables.tfvars.hcl centos_packer.pkr.hcl
              
